### ISSUE TITLE
this addon breaks pulling zone dungeon data for mouseover tooltip in classic 1.15.0

### ISSUE THREAD

**Issue by Kewlie** [thurin/HydraUI_LocationPlus#2]
im not sure when blizzard broke this, i would assume probably with the 1.13 patch for classic era, ill try my best to get you the bug report from bug grabber

4x HydraUI_LocationPlus/HydraUI_LocationPlus.lua:192: attempt to call method 'GetInstanceAltGroupSize' (a nil value)
[string "@HydraUI_LocationPlus/HydraUI_LocationPlus.lua"]:192: in function <HydraUI_LocationPlus/HydraUI_LocationPlus.lua:187>
[string "@HydraUI_LocationPlus/HydraUI_LocationPlus.lua"]:309: in function <HydraUI_LocationPlus/HydraUI_LocationPlus.lua:239>

Locals:
dungeon = "Wailing Caverns"
name = "Kalimdor"
instanceType = "none"
difficultyID = 0
difficultyName = ""
maxPlayers = 0
dynamicDifficulty = 0
isDynamic = false
instanceID = 1
instanceGroupSize = 0
LfgDungeonID = nil
low = 15
high = 25
r = 1
g = 0.900000
b = 0
groupSize = 5
(*temporary) = nil
(*temporary) = <table> {
 GetGatheringSkillColor = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:991
 GetLevel = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:752
 IterateEasternKingdoms = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1416
 IsInKalimdor = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1527
 GetBestZoneCoordinate = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:949
 IterateAlliance = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1352
 HasRecommendedInstances = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1431
 GetInstanceZone = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1201
 IsZoneOrInstance = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1463
 GetHBD = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:32
 IterateZoneInstances = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1113
 IsInstance = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1435
 GetFishingLevelString = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:745
 IterateHostile = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1352
 IteratePvPZones = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1338
 GetType = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1458
 IterateContested = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1388
 IterateComplexes = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1324
 IsZone = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1441
 GetMapZonesAlt = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:631
 IterateZoneComplexes = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1180
 GetFlightnodeLookupTable = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:542
 DoesZoneHaveComplexes = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1249
 IterateHorde = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1366
 GetComplex = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:1453
 GetMiningSkillColor = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:6855
 IterateHerbs = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:5125
 IterateMiningNodes = <function> defined @HydraUI_LocationPlus/Libs/LibTouristClassicEra/LibTouristClassicEra.lua:6876
 GetMapNameByIDAlt = <function> defined @Inter
 
 actually looking at the bottom of that error kind of tells me this addon just needs a library update possibly?

**Comment by thurin** [comment]
should be resolved in 1.10

**Comment by Kewlie** [comment]
just updated it, semms to work as expected now thanks for your hard work
